version: '3.5'

services:
  app1: &app
    build: .
    hostname: app1
    container_name: app1
    environment:
      - LOCAL_ENDPOINT=http://database:8000
    depends_on:
      - database
    networks:
      - netapi
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "180MB"

  app2:
    <<: *app
    hostname: app2
    container_name: app2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - netapi
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  database:
    image: amazon/dynamodb-local
    networks:
      - netapi
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "200MB"

networks:
  netapi:
    driver: bridge